### ISSUE TITLE
Does it work with python 3.7?

### ISSUE THREAD

**Issue by lsampaioweb** [openzipkin/pyramid_zipkin-example#3]
I have python 3.7 on my Mac OS (High Sierra) and when I try to run "python3 frontend.py" or "python3 backend.py" I get the following error message:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/path.py", line 380, in _zope_dottedname_style
    found = getattr(found, n)
AttributeError: module 'pyramid_zipkin' has no attribute 'tween'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frontend.py", line 40, in <module>
    main()
  File "frontend.py", line 29, in main
    config.include('pyramid_zipkin')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/config/__init__.py", line 839, in include
    c(configurator)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid_zipkin/__init__.py", line 9, in includeme
    config.add_tween('pyramid_zipkin.tween.zipkin_tween', over=EXCVIEW)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/config/tweens.py", line 107, in add_tween
    explicit=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/util.py", line 590, in wrapper
    result = wrapped(self, *arg, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/config/tweens.py", line 126, in _add_tween
    tween_factory = self.maybe_dotted(tween_factory)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/config/__init__.py", line 912, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid/path.py", line 382, in _zope_dottedname_style
    __import__(used)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyramid_zipkin/tween.py", line 5, in <module>
    import py_zipkin.stack
ModuleNotFoundError: No module named 'py_zipkin.stack'

----------------------------------------------------------------------------------------------------
Running "pip3 list" I get:

Package                Version  
-------------------------------
certifi                 2018.8.13
chardet                3.0.4    
Cython                 0.28.5   
hupper                 1.3      
idna                   2.7      
PasteDeploy            1.5.2    
pip                    18.0     
plaster                1.0      
plaster-pastedeploy    0.6      
ply                    3.11     
py-zipkin              0.13.0   
pyramid                1.9.2    
pyramid-zipkin         0.21.0   
pyramid-zipkin-example 0.1      
repoze.lru                    0.7      
requests                      2.19.1   
setuptools                  40.0.0   
six                                1.11.0   
thriftpy                        0.3.9    
translationstring         1.3      
urllib3                          1.23     
venusian                      1.1.0    
WebOb                        1.8.2    
zope.deprecation       4.3.0    
zope.interface            4.5.0

**Comment by drolando** [comment]
The problem here is not python 3.7.

There was a backward incompatible change in py-zipkin 0.13. pyramid_zipkin >= 0.21.1 was patched to support it, but you're using 0.21.0.

If you bump all the libraries to the latest version everything should work.

**Comment by katyucha** [comment]
Hi ! Same problem but can't find 0.21.1 version

```
# pip3 install pyramid-zipkin==0.21.1
Collecting pyramid-zipkin==0.21.1
  Could not find a version that satisfies the requirement pyramid-zipkin==0.21.1 (from versions: 0.4.0, 0.4.1, 0.9.1, 0.11.1, 0.13.0, 0.14.0, 0.15.0, 0.16.1, 0.17.0, 0.18.0, 0.18.1, 0.18.2, 0.19.2, 0.20.0, 0.20.2, 0.20.3, 0.21.0)
No matching distribution found for pyramid-zipkin==0.21.1
```

**Comment by drolando** [comment]
Whoops sorry, I just realized we haven't configured travis to upload new versions of pyramid-zipkin to the public pypi.

I've just uploaded the new wheels and this should now work.
